---
title: "`r params$district` District Performance"
author: "<br> Office of Accountability <br> Tennessee Department of Education"
output:
    revealjs::revealjs_presentation:
        theme: default
params:
    district: NA
    year: NA
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(rbokeh)

ach_profile <- read_csv("data/achievement_profile_data_2015_2016.csv") %>%
    filter(Year == params$year)
```

This is a report for `r params$district` for the `r params$year` school year.

## Demographic Data

```{r demographics}
ach_profile %>%
    filter(District == params$district) %>%
    mutate(District = factor(District, levels = c(params$district, "State of Tennessee"))) %>% 
    select(`Number of Schools`, Enrollment:Expenditures) %>%
    gather(Characteristic, Value, `Number of Schools`:Expenditures) %>% 
    knitr::kable()
```

## Achievement

```{r achievement}

if (params$district < "State of Tennessee") {
    color_palette <- c("#1f77b4", "#d62728")
} else {
    color_palette <- c("#d62728", "#1f77b4")
}

ach_profile %>%
    filter(District %in% c(params$district, "State of Tennessee")) %>%
    mutate(District = factor(District, levels = c(params$district, "State of Tennessee"))) %>%
    select(District, ELA:`US History`) %>%
    gather(Subject, Value, -District) %>%
    group_by(Subject) %>%
    mutate(Count = sum(!is.na(Value))) %>%
    filter(Count == 2) %>%
    figure(xlab = "", ylab = "Percent On Track/Mastered", padding_factor = 0, tools = NULL) %>%
        ly_bar(x = Subject, y = Value, hover = TRUE, color = District, position = "dodge") %>%
        y_range(c(0, 100)) %>%
        set_palette(discrete_color = pal_color(color_palette))
```

## TVAAS

```{r tvaas}
ach_profile %>%
    filter(District == params$district) %>%
    select(starts_with("TVAAS")) %>%
    knitr::kable()
```

## Ready Graduates

```{r ready_grad}

if (params$district < "State of Tennessee") {
    color_palette <- c("#1f77b4", "#d62728")
} else {
    color_palette <- c("#d62728", "#1f77b4")
}

ach_profile %>%
    filter(District %in% c(params$district, "State of Tennessee")) %>%
    mutate(District = factor(District, levels = c(params$district, "State of Tennessee"))) %>%
    select(District, Grad, `ACT 21 or Above`) %>%
    rename(`Graduation Rate` = Grad) %>%
    gather(Subject, Value, -District) %>%
    group_by(Subject) %>%
    mutate(Count = sum(!is.na(Value))) %>%
    filter(Count == 2) %>% 
    figure(xlab = "", ylab = "Percent", xlim = c("Graduation Rate", "ACT 21 or Above"),
           padding_factor = 0, tools = NULL) %>%
    ly_bar(x = Subject, y = Value, hover = TRUE, color = District, position = "dodge") %>%
    y_range(c(0, 100)) %>%
    set_palette(discrete_color = pal_color(color_palette))
```
