---
output: 
    word_document:
        reference_docx: template.docx
params:
    district: NA
    year: NA
---

## `r params$district` District Report

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(ggthemes)

ach_profile <- read_csv("data/achievement_profile_data_2015_2016.csv") %>%
    filter(Year == params$year)
```

This is a report for `r params$district` for the `r params$year` school year.

&nbsp;

Here is demographic data for `r params$district`:

```{r demographics}
ach_profile %>%
    filter(District == params$district) %>%
    mutate(District = factor(District, levels = c(params$district, "State of Tennessee"))) %>% 
    select(`Number of Schools`, Enrollment, Black, Hispanic, Native, EL, SWD, ED, Expenditures) %>%
    gather(Characteristic, Value, `Number of Schools`:Expenditures) %>% 
    knitr::kable()
```

&nbsp;

Here is achievement data in accountability subjects for `r params$district`:

```{r achievement}
ach_profile %>%
    filter(District %in% c(params$district, "State of Tennessee")) %>%
    mutate(District = factor(District, levels = c(params$district, "State of Tennessee"))) %>% 
    select(District, `Algebra I`, `Algebra II`, `Geometry`, `English I`, `English II`, `English III`) %>%
    gather(Subject, `Percent On Track/Mastered`, -District) %>%
    group_by(Subject) %>%
    mutate(Count = sum(!is.na(`Percent On Track/Mastered`))) %>%
    filter(Count == 2) %>%
    ggplot(aes(x = Subject, y = `Percent On Track/Mastered`, fill = District)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_text(aes(label = `Percent On Track/Mastered`), position = position_dodge(width = 0.9), vjust = -0.25) +
        scale_y_continuous(limits = c(0, 100)) +
        theme_hc() +
        theme(legend.position = "bottom",
            axis.title.x = element_blank())
```

&nbsp;

Here are TVAAS scores for `r params$district`:

```{r tvaas}
ach_profile %>%
    filter(District == params$district) %>% 
    select(starts_with("TVAAS")) %>%
    knitr::kable()
```

&nbsp;

Here is postsecondary data for `r params$district`:

```{r ready_grad}
ach_profile %>%
    filter(District %in% c(params$district, "State of Tennessee")) %>%
    mutate(District = factor(District, levels = c(params$district, "State of Tennessee"))) %>% 
    select(District, `Grad`, `ACT 21 or Above`) %>%
    gather(Subject, Percent, -District) %>%
    group_by(Subject) %>%
    mutate(Count = sum(!is.na(Percent))) %>%
    filter(Count == 2) %>%
    ggplot(aes(x = Subject, y = Percent, fill = District)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_text(aes(label = Percent), position = position_dodge(width = 0.9), vjust = -0.25) +
        scale_y_continuous(limits = c(0, 100)) +
        theme_hc() +
        theme(legend.position = "bottom",
            axis.title.x = element_blank())
```

